name        : debates_venv
channels    :
  - conda-forge
  - anaconda
  - conda
dependencies:
  - python=3.10
  - scikit-learn
  - wandb
  - seaborn
  - loguru
  - sentence-transformers
  - matplotlib
  - pip:
      - pykeen
      - rootutils
      - openpyxl